### ISSUE TITLE
use cffi-grovel for more accurate struct representations

### ISSUE THREAD

**Issue by orthecreedence** [orthecreedence/cl-libuv#2]

**Comment by orthecreedence** [comment]
@ivan4th, can you point me in the direction of a project that uses cffi-groveler extensively? The docs are sparse and I'd like some examples to go off of. I would like to eventually use this method instead of the fairly fragile swig/cffi method.

**Comment by ivan4th** [comment]
Well, from quicklisp system info we get:
```
ivan4th@think:~/quicklisp/dists/quicklisp$ grep cffi-grovel ~/quicklisp/dists/quicklisp/systems.txt |sed 's/ .*//'|sort|uniq
antik
basic-binary-ipc
cffi
cl-fam
cl-freetype2
cl-fsnotify
cl-fuse
cl-gss
cl-inotify
cl-libusb
cl-llvm
cl-m4
cl-mpi
cl-png
cl-proc
cl-rlimit
cl-v4l2
cl-zmq
gsll
hdf5-cffi
inotify
lisp-zmq
magicffi
mixalot
osicat
pzmq
static-vectors
trivial-features
```
Perhaps some of these may give a hint.

**Comment by orthecreedence** [comment]
Should have been closed ages ago, we use grovel now.
