### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [orthecreedence/cl-libuv#23]
Building with SBCL 2.3.3.83-562a1a329 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 19fbd1a22105921a8b7b0691e9e643ae8b1db024

*cl-libuv* fails to build with the following error:

```
; caught ERROR:
;   (during macroexpansion of (DEFCFUN ("uv_loop_size" UV-LOOP-SIZE) ...))
;   Unknown CFFI type SIZE-T
...
; caught ERROR:
;   (during macroexpansion of (DEFCFUN ("uv_now" UV-NOW) ...))
;   Unknown CFFI type UINT64-T
...
; caught ERROR:
;   (during macroexpansion of (DEFCFUN ("uv_handle_size" UV-HANDLE-SIZE) ...))
;   Unknown CFFI type UV-HANDLE-TYPE
...
; caught ERROR:
;   (during macroexpansion of (DEFCFUN ("uv_req_size" UV-REQ-SIZE) ...))
;   Unknown CFFI type UV-REQ-TYPE
...
; caught ERROR:
;   (during macroexpansion of (DEFCFUN ("uv_guess_handle" UV-GUESS-HANDLE) ...))
;   Unknown CFFI type UV-HANDLE-TYPE
...
; caught ERROR:
;   (during macroexpansion of (DEFCFUN ("uv_pipe_pending_type" UV-PIPE-PENDING-TYPE) ...))
;   Unknown CFFI type UV-HANDLE-TYPE
...
; caught ERROR:
;   (during macroexpansion of (DEFCFUN ("uv_timer_start" UV-TIMER-START) ...))
;   Unknown CFFI type UINT64-T
...
; caught ERROR:
;   (during macroexpansion of (DEFCFUN ("uv_timer_set_repeat" UV-TIMER-SET-REPEAT) ...))
;   Unknown CFFI type UINT64-T
...
; caught ERROR:
;   (during macroexpansion of (DEFCFUN ("uv_timer_get_repeat" UV-TIMER-GET-REPEAT) ...))
;   Unknown CFFI type UINT64-T
...
Unhandled CFFI::UNDEFINED-FOREIGN-TYPE-ERROR in thread #<SB-THREAD:THREAD tid=3303063 "main thread" RUNNING {1001738003}>: Unknown CFFI type UV-UID-T

```

[Full log here](http://report.quicklisp.org/2023-05-25/failure-report/cl-libuv.html)

**Comment by quicklisp** [comment]
This impacts a lot of other systems that depend on cl-libuv.

**Comment by quicklisp** [comment]
I'm not sure. Maybe it interacts badly with recent updates to cffi?

Do you see the build problem also?

**Comment by orthecreedence** [comment]
Are you able to test if rolling back https://github.com/orthecreedence/cl-libuv/commit/19fbd1a22105921a8b7b0691e9e643ae8b1db024 fixes the issue? If so I can just revert it, otherwise if this is a larger CFFI issue I don't really have the time to properly debug this. I haven't really touched it in years.

**Comment by quicklisp** [comment]
Hmm,  now I can't reproduce the error. I'm going to dig a bit more.

**Comment by quicklisp** [comment]
I asked about this on the cffi list and got this reply from Madhu:



No, the problem is in libuv commit dd6df070e0e34 on 2023-05-23
21:56:08 which introduces a form at the top of the file grovel.lisp:

```
 (in-package :libuv)

+#.(when (uiop:getenv "HOMEBREW_PREFIX")
+    (pushnew :homebrew *features*)
+    (values))
+
```

This fools the loop in grovel/grove.lisp (generate-c-file) which has
```
   (flet ((read-forms (s)
            (do ((forms ())
                 (form (read s nil nil) (read s nil nil)))
                ((null form) (nreverse forms))
```

The first form is "(in-package :libuv)"

If your environment doesn't have HOMEBREW_PREFIX the second form is
read with READ-EVAL T as NIL and the reader loop exits and you end up
with an empty  C file with nothing other than the inpackage form.

You could change the loop, but I'd suggest that you don't use
top-level reader conditionals in the grovel.lisp file, set up the features
outside of the grovel.lisp file.
