### ISSUE TITLE
msys2 support

### ISSUE THREAD

**Issue by podiki** [orthecreedence/cl-libuv#8]
MSYS2 (Windows) uses a slightly different name for the library, "libuv-1.dll". I created pull request #7 to fix this.

**Comment by orthecreedence** [comment]
Merged!

**Comment by podiki** [comment]
Thanks, but I'm not seeing the fix merged on github...

**Comment by orthecreedence** [comment]
Weird, what the hell. I definitely merged it, but now it just gave me the option to merge again.

**Comment by podiki** [comment]
Looks good now!
